const state={guilds:[],guildId:"",features:{},view:"overview",me:null,timer:null};
const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
async function request(path,opts={}){const r=await fetch("/api/v1"+path,{...opts,cache:"no-store",headers:{"Cache-Control":"no-cache",...(opts.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||"Request failed");return d}
function setupUser(){const u=state.me.user||{};$("#loginBtn").hidden=true;$("#logoutBtn").hidden=false;$("#userName").textContent=u.global_name||u.username||"User";$("#userAvatar").textContent=(u.global_name||u.username||"C")[0].toUpperCase();$("#adminBadge").textContent=state.me.superAdmin?"SUPER ADMIN":"CONTROL ACCESS";$("#adminBadge").classList.toggle("super",!!state.me.superAdmin)}
function populateServers(){const s=$("#guildSelect");s.innerHTML='<option value="">Select server</option>'+state.guilds.map(g=>\`<option value="${g.id}">${esc(g.name)}${g.botInstalled?"":" — Install Core"}</option>\`).join("");renderServerStrip()}
function renderServerStrip(){const el=$("#serverStrip");if(!state.guilds.length){el.innerHTML="";return}el.innerHTML='<div class="server-strip">'+state.guilds.map(g=>\`<button class="server-mini ${state.guildId===g.id?"selected":""}" data-server="${g.id}"><span class="server-icon">${g.icon?\`<img src="${esc(g.icon)}" alt="">\`:esc(g.name[0]||"C")}</span><span class="server-copy"><b>${esc(g.name)}</b><small>${g.botInstalled?"CORE INSTALLED":"INSTALL CORE"}</small></span><i class="dot ${g.botInstalled?"ok":""}"></i></button>\`).join("")+'</div>';document.querySelectorAll("[data-server]").forEach(b=>b.onclick=()=>{state.guildId=b.dataset.server;$("#guildSelect").value=state.guildId;render(state.view)})}
function featureGroups(v){return{moderation:[["moderation","Moderation","Moderation commands and actions.","</>"],["automod","AutoMod","Automated content protection.","//"]],protection:[["protection","Protection","Core server protection controls.","◈"],["anti_raid","Anti-Raid","Additional raid safeguards.","!!"]],logging:[["logger","Logger","Member, message, voice and system logs."," >_"],["advanced_logs","Advanced Logs","Extended audit visibility.","{}"]],welcome:[["welcome","Welcome","Member onboarding and welcome flow.","</>"],["welcome.dm.enabled","Welcome DM","Private welcome messages.","DM"],["welcome.goodbye.enabled","Goodbye","Departure messages.","<-"],["welcome.autoRole.enabled","Auto Role","Automatic role assignment.","#"]] }[v]||[]}
async function boot(){try{const h=await fetch("/health",{cache:"no-store"}).then(r=>r.json());$("#apiStatus")&&($("#apiStatus").textContent=h.ok?"online":"offline");const r=await fetch("/api/auth/me",{cache:"no-store"});if(!r.ok){renderLogin();return}state.me=await r.json();state.guilds=state.me.guilds||[];setupUser();populateServers();if(!state.guildId)state.guildId=state.guilds.find(g=>g.botInstalled)?.id||state.guilds[0]?.id||"";$("#guildSelect").value=state.guildId;await render(state.view);clearInterval(state.timer);state.timer=setInterval(()=>{if(!document.hidden&&state.guildId)render(state.view)},15000)}catch(e){$("#content").innerHTML=\`<div class="empty error">Core API connection failed.<br><small>${esc(e.message)}</small></div>\`}}
function renderLogin(){$("#loginBtn").hidden=false;$("#logoutBtn").hidden=true;$("#content").innerHTML='<div class="login-hero"></div><div class="install-card"><div class="code-icon">&lt;/&gt;</div><h2>CODERYX Core Console</h2><p>Developer-grade Discord bot control, built for speed and clarity.</p><a class="primary-btn" href="/api/auth/discord">Continue with Discord</a></div>'}
async function render(v){state.view=v;const titles={overview:"Overview",servers:"Servers",moderation:"Moderation",protection:"Protection",logging:"Logging",welcome:"Welcome"};$("#pageTitle").textContent=titles[v]||"Overview";document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.view===v));renderServerStrip();if(v==="servers"){renderServers();return}const selected=state.guilds.find(g=>g.id===state.guildId);if(!selected){$("#content").innerHTML='<div class="empty"><b>Select a Discord server</b><br><small>Choose a server from the top bar.</small></div>';return}if(!selected.botInstalled){$("#content").innerHTML=\`<div class="install-card"><div class="code-icon">&lt;/&gt;</div><h2>Core is not installed</h2><p>Install CODERYX Core in <b>${esc(selected.name)}</b> to manage it here.</p><a class="primary-btn" href="https://discord.com/oauth2/authorize?client_id=${encodeURIComponent(window.CORE_CLIENT_ID||"")}&permissions=8&scope=bot%20applications.commands" target="_blank">Install Core</a></div>\`;return}try{const [summary,features]=await Promise.all([request(\`/guilds/${state.guildId}/summary\`),request(\`/guilds/${state.guildId}/features\`)]);state.features=features;if(v==="overview")overview(summary);else featureView(v,summary)}catch(e){$("#content").innerHTML=\`<div class="empty error">${esc(e.message)}</div>\`}}
function overview(s){const enabled=Object.values(state.features).filter(Boolean).length,total=Object.keys(state.features).length;$("#content").innerHTML=\`<div class="hero-card"><div class="hero-grid"><div><span class="eyebrow">ACTIVE WORKSPACE</span><h2>${esc(s.name)}</h2><p>Core is connected. Configuration changes are applied immediately without restarting the bot.</p></div><div class="hero-code"><span>const core =</span><b>ready();</b><i>// 01</i></div></div></div><div class="stats-grid"><div class="stat-card"><small>MEMBERS</small><strong>${s.memberCount??"—"}</strong><span>Discord community</span></div><div class="stat-card"><small>CHANNELS</small><strong>${s.channels??"—"}</strong><span>Server structure</span></div><div class="stat-card"><small>ACTIVE FEATURES</small><strong>${enabled}<em>/${total}</em></strong><span>Live configuration</span></div><div class="stat-card"><small>CORE STATUS</small><strong class="live">ONLINE</strong><span>Discord connection</span></div></div><div class="section-head"><div><span class="eyebrow">QUICK CONTROL</span><h3>Core modules</h3></div><button class="ghost-btn" id="refresh">↻ Sync</button></div><div class="module-grid">${[["moderation","Moderation","Moderation commands and actions.","</>"],["protection","Protection","Security and anti-raid controls.","◈"],["logging","Logging","Event logs and audit visibility."," >_"],["welcome","Welcome","Onboarding and member flow.","</>"]].map(x=>moduleCard(...x)).join("")}</div>\`;$("#refresh").onclick=()=>render("overview");document.querySelectorAll("[data-module]").forEach(b=>b.onclick=()=>render(b.dataset.module))}
function moduleCard(v,n,d,i){const rows=featureGroups(v),on=rows.some(x=>state.features[x[0]]);return\`<button class="module-card" data-module="${v}"><span class="module-icon">${i}</span><b>${n}</b><small>${d}</small><span class="${on?"module-on":""}">${on?"● Enabled":"○ Disabled"} · Open →</span></button>\`}
function renderServers(){$("#content").innerHTML=\`<div class="section-head"><div><span class="eyebrow">DISCORD ACCESS</span><h3>Your servers</h3></div><button class="ghost-btn" id="sync">↻ Sync</button></div><div class="server-grid">${state.guilds.map(g=>\`<button class="server-tile" data-server="${g.id}"><span class="server-icon large">${g.icon?\`<img src="${esc(g.icon)}" alt="">\`:esc(g.name[0]||"C")}</span><div><b>${esc(g.name)}</b><small>${g.botInstalled?"Core installed · Ready":"Core not installed"}</small></div><span class="status-pill ${g.botInstalled?"ok":""}">${g.botInstalled?"READY":"INSTALL"}</span></button>\`).join("")}</div>\`;document.querySelectorAll(".server-tile").forEach(b=>b.onclick=()=>{state.guildId=b.dataset.server;$("#guildSelect").value=state.guildId;render("overview")});$("#sync").onclick=boot}
function featureView(v,s){const rows=featureGroups(v);$("#content").innerHTML=\`<div class="feature-heading"><div><span class="eyebrow">${esc(s.name)} / CORE CONFIG</span><h2>${v[0].toUpperCase()+v.slice(1)} controls</h2><p>Changes save immediately and are reflected by the bot without a restart.</p></div><span class="live-badge">● LIVE</span></div><div class="feature-list">${rows.map(([k,n,d])=>\`<div class="feature-row"><div><b>${esc(n)}</b><small>${esc(d)}</small><code>${esc(k)}</code></div><button class="switch ${state.features[k]?"on":""}" data-feature="${esc(k)}" aria-pressed="${!!state.features[k]}"><span></span></button></div>\`).join("")}</div>\`;document.querySelectorAll(".switch").forEach(b=>b.onclick=()=>toggle(b,b.dataset.feature))}
async function toggle(b,k){const enabled=!b.classList.contains("on");b.disabled=true;try{await request(\`/guilds/${state.guildId}/features\`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({feature:k,enabled})});state.features[k]=enabled;b.classList.toggle("on",enabled);b.setAttribute("aria-pressed",String(enabled));toast(enabled?"Feature enabled":"Feature disabled")}catch(e){toast(e.message,true)}finally{b.disabled=false}}
function toast(m,error=false){const t=$("#toast");t.textContent=m;t.className="toast "+(error?"error":"");requestAnimationFrame(()=>t.classList.add("show"));clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),2200)}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>render(b.dataset.view));$("#guildSelect").onchange=e=>{state.guildId=e.target.value;render(state.view)};boot();
